import { Permission } from './permissions';
import {
  TENANT_VIEW, TENANT_UPDATE,
  TEAM_VIEW, TEAM_INVITE, TEAM_UPDATE_ROLE, TEAM_REVOKE,
  BILLING_VIEW, BILLING_MANAGE, SUBSCRIPTION_UPGRADE, SUBSCRIPTION_DOWNGRADE,
  TELEPHONY_VIEW, TELEPHONY_MANAGE,
  INTEGRATIONS_VIEW, INTEGRATIONS_MANAGE,
  AI_AGENT_VIEW, AI_AGENT_CREATE, AI_AGENT_UPDATE, AI_AGENT_DELETE,
  AI_PROMPT_VIEW, AI_PROMPT_UPDATE,
  AI_VOICE_MANAGE, AI_KNOWLEDGE_MANAGE,
  CAMPAIGN_VIEW, CAMPAIGN_CREATE, CAMPAIGN_UPDATE, CAMPAIGN_EXECUTE, CAMPAIGN_PAUSE,
  LEAD_VIEW, LEAD_CREATE, LEAD_UPDATE, LEAD_DELETE, LEAD_IMPORT, LEAD_ASSIGN, LEAD_EXPORT,
  CALL_VIEW, CALL_INITIATE, CALL_MONITOR, CALL_INTERVENE, CALL_DISPOSITION,
  RECORDING_VIEW, RECORDING_EXPORT,
  ANALYTICS_VIEW, ANALYTICS_EXPORT,
  AUTOMATION_VIEW, AUTOMATION_CREATE, AUTOMATION_UPDATE, AUTOMATION_EXECUTE,
  CALENDAR_VIEW, CALENDAR_MANAGE,
  SECURITY_VIEW, SECURITY_MANAGE,
  AUDIT_LOG_VIEW,
  WORKSPACE_VIEW, WORKSPACE_MANAGE,
  PLATFORM_TENANT_CREATE, PLATFORM_TENANT_MANAGE,
  PLATFORM_TELEPHONY, PLATFORM_AI_PROVIDERS,
  PLATFORM_BILLING_CONFIG, PLATFORM_DIAGNOSTICS, PLATFORM_AUDIT,
} from './permissions';

/**
 * Role → Permissions mapping.
 * Default is DENY. Only explicitly listed permissions are granted.
 *
 * super_admin has ALL permissions (platform + tenant).
 * Tenant roles have only tenant-scoped permissions.
 */
export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  super_admin: [
    // Platform permissions
    PLATFORM_TENANT_CREATE,
    PLATFORM_TENANT_MANAGE,
    PLATFORM_TELEPHONY,
    PLATFORM_AI_PROVIDERS,
    PLATFORM_BILLING_CONFIG,
    PLATFORM_DIAGNOSTICS,
    PLATFORM_AUDIT,
    // All tenant permissions (super_admin can act on any tenant)
    TENANT_VIEW,
    TENANT_UPDATE,
    TEAM_VIEW, TEAM_INVITE, TEAM_UPDATE_ROLE, TEAM_REVOKE,
    BILLING_VIEW, BILLING_MANAGE, SUBSCRIPTION_UPGRADE, SUBSCRIPTION_DOWNGRADE,
    TELEPHONY_VIEW, TELEPHONY_MANAGE,
    INTEGRATIONS_VIEW, INTEGRATIONS_MANAGE,
    AI_AGENT_VIEW, AI_AGENT_CREATE, AI_AGENT_UPDATE, AI_AGENT_DELETE,
    AI_PROMPT_VIEW, AI_PROMPT_UPDATE,
    AI_VOICE_MANAGE, AI_KNOWLEDGE_MANAGE,
    CAMPAIGN_VIEW, CAMPAIGN_CREATE, CAMPAIGN_UPDATE, CAMPAIGN_EXECUTE, CAMPAIGN_PAUSE,
    LEAD_VIEW, LEAD_CREATE, LEAD_UPDATE, LEAD_DELETE, LEAD_IMPORT, LEAD_ASSIGN, LEAD_EXPORT,
    CALL_VIEW, CALL_INITIATE, CALL_MONITOR, CALL_INTERVENE, CALL_DISPOSITION,
    RECORDING_VIEW, RECORDING_EXPORT,
    ANALYTICS_VIEW, ANALYTICS_EXPORT,
    AUTOMATION_VIEW, AUTOMATION_CREATE, AUTOMATION_UPDATE, AUTOMATION_EXECUTE,
    CALENDAR_VIEW, CALENDAR_MANAGE,
    SECURITY_VIEW, SECURITY_MANAGE,
    AUDIT_LOG_VIEW,
    WORKSPACE_VIEW, WORKSPACE_MANAGE,
  ],

  company_admin: [
    TENANT_VIEW, TENANT_UPDATE,
    TEAM_VIEW, TEAM_INVITE, TEAM_UPDATE_ROLE, TEAM_REVOKE,
    BILLING_VIEW, BILLING_MANAGE, SUBSCRIPTION_UPGRADE, SUBSCRIPTION_DOWNGRADE,
    TELEPHONY_VIEW, TELEPHONY_MANAGE,
    INTEGRATIONS_VIEW, INTEGRATIONS_MANAGE,
    AI_AGENT_VIEW, AI_AGENT_CREATE, AI_AGENT_UPDATE, AI_AGENT_DELETE,
    AI_PROMPT_VIEW, AI_PROMPT_UPDATE,
    AI_VOICE_MANAGE, AI_KNOWLEDGE_MANAGE,
    CAMPAIGN_VIEW, CAMPAIGN_CREATE, CAMPAIGN_UPDATE, CAMPAIGN_EXECUTE, CAMPAIGN_PAUSE,
    LEAD_VIEW, LEAD_CREATE, LEAD_UPDATE, LEAD_DELETE, LEAD_IMPORT, LEAD_ASSIGN, LEAD_EXPORT,
    CALL_VIEW, CALL_INITIATE, CALL_MONITOR, CALL_INTERVENE, CALL_DISPOSITION,
    RECORDING_VIEW, RECORDING_EXPORT,
    ANALYTICS_VIEW, ANALYTICS_EXPORT,
    AUTOMATION_VIEW, AUTOMATION_CREATE, AUTOMATION_UPDATE, AUTOMATION_EXECUTE,
    CALENDAR_VIEW, CALENDAR_MANAGE,
    SECURITY_VIEW, SECURITY_MANAGE,
    AUDIT_LOG_VIEW,
    WORKSPACE_VIEW, WORKSPACE_MANAGE,
  ],

  manager: [
    TENANT_VIEW,
    TEAM_VIEW,
    AI_AGENT_VIEW, AI_AGENT_CREATE, AI_AGENT_UPDATE,
    AI_PROMPT_VIEW, AI_PROMPT_UPDATE,
    AI_VOICE_MANAGE, AI_KNOWLEDGE_MANAGE,
    CAMPAIGN_VIEW, CAMPAIGN_CREATE, CAMPAIGN_UPDATE, CAMPAIGN_EXECUTE, CAMPAIGN_PAUSE,
    LEAD_VIEW, LEAD_CREATE, LEAD_UPDATE, LEAD_IMPORT, LEAD_ASSIGN,
    CALL_VIEW, CALL_INITIATE, CALL_MONITOR, CALL_INTERVENE, CALL_DISPOSITION,
    RECORDING_VIEW,
    ANALYTICS_VIEW,
    AUTOMATION_VIEW, AUTOMATION_CREATE, AUTOMATION_UPDATE, AUTOMATION_EXECUTE,
    CALENDAR_VIEW, CALENDAR_MANAGE,
    AUDIT_LOG_VIEW,
    WORKSPACE_VIEW,
  ],

  agent: [
    TEAM_VIEW,
    LEAD_VIEW, LEAD_UPDATE,
    CALL_VIEW, CALL_DISPOSITION,
    RECORDING_VIEW,
    AUTOMATION_VIEW,
    WORKSPACE_VIEW,
  ],

  viewer: [
    TENANT_VIEW,
    TEAM_VIEW,
    AI_AGENT_VIEW,
    LEAD_VIEW,
    CALL_VIEW,
    RECORDING_VIEW,
    ANALYTICS_VIEW,
    AUTOMATION_VIEW,
    CALENDAR_VIEW,
    AUDIT_LOG_VIEW,
    WORKSPACE_VIEW,
  ],
};

/**
 * Check if a role has a specific permission.
 */
export function hasPermission(role: string, permission: Permission): boolean {
  const perms = ROLE_PERMISSIONS[role];
  if (!perms) return false;
  return perms.includes(permission);
}

/**
 * Check if a role has ALL of the specified permissions.
 */
export function hasAllPermissions(role: string, permissions: Permission[]): boolean {
  return permissions.every(p => hasPermission(role, p));
}

/**
 * Check if a role has ANY of the specified permissions.
 */
export function hasAnyPermission(role: string, permissions: Permission[]): boolean {
  return permissions.some(p => hasPermission(role, p));
}
